# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftBasic01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftBasic01

  target 'SwiftBasic01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftBasic01UITests' do
    # Pods for testing
  end

end
